local H = dofile(vim.fs.dirname(arg[0]) .. "/helpers.lua")
H.setup_rtp()
vim.env.XDG_CONFIG_HOME = H.tmpdir()
vim.keymap.set("n", "ySS", ":echo 'personal'<CR>")
dofile(H.root() .. "/config/init.lua")
H.eq(vim.fn.maparg("ySS", "n"), ":echo 'personal'<CR>", "personal surround mapping wins")
H.eq(vim.g.colors_name, "molokai", "managed editor uses Molokai")
H.eq(vim.api.nvim_get_hl(0, { name = "Normal" }).bg, 0x1B1D1E,
  "Molokai's original dark background is preserved")
H.eq(vim.wo.smoothscroll, false, "managed scrolling retains the original behavior")
H.eq(vim.g.loaded_surround, 1, "surround ships offline in managed mode")
local function edit(line, keys)
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { line })
  vim.api.nvim_win_set_cursor(0, {1, 0})
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(keys, true, false, true), "xt", false)
  return vim.api.nvim_get_current_line()
end
H.eq(edit('"hello"', [[cs"']]), "'hello'", "cs changes surrounding quotes")
H.eq(edit('"hello"', [[ds"]]), "hello", "ds removes surrounding quotes")
H.eq(edit('hello', 'ysiw)'), '(hello)', "ys surrounds a text object")
H.eq(edit('hello', 'viwS]'), '[hello]', "visual S surrounds the selection")
H.finish()
